#!/bin/bash

CONFIG=docker-compose.e2e.yml

if which docker-compose >/dev/null; then
				docker-compose -f $CONFIG stop
				docker-compose -f $CONFIG rm -f test-db test-redis
else
				docker compose -f $CONFIG stop
				docker compose -f $CONFIG rm -f test-db test-redis
fi
