version: "3.8"

services:
  test-db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  test-redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379

