version: "3.8"

services:
  api:
    build: .
    restart: always
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: bash -c 'while !</dev/tcp/db/5432 || !</dev/tcp/redis/6379; do sleep 1; done; npm run start:dev'
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379

